name: CI

on: [push, pull_request]

jobs:
  build-jar:
    name: 'Build fat jar'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: mabe02/lanterna
          ref: refs/heads/release/3.1
          path: lanterna

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install lanterna
        run: mvn -f lanterna/pom.xml install -Dmaven.test.skip=true

      - name: Build fat jar
        run: |
          ./gradlew shadowJar

      - name: Get version number
        run: |
          echo "VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV

      - name: Publish fat jar
        uses: actions/upload-artifact@v2-preview
        with:
          name: bat-${{ env.VERSION }}.jar
          path: build/libs/*-all.jar

      - name: 'Create Release'
        if: contains(github.ref, 'v')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}
          body: |
            Initial release
          draft: false
          prerelease: false

      - name: 'Upload Release Asset'
        if: contains(github.ref, 'v')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: build/libs/batarang-${{env.VERSION}}-all.jar
          asset_name: bat-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive

      - name: 'Write Upload URL To File'
        if: contains(github.ref, 'v')
        run: |
          echo "${{steps.create_release.outputs.upload_url}}" > upload_url.txt

      - name: 'Publish Upload URL'
        if: contains(github.ref, 'v')
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'upload_url.txt'
          path: 'upload_url.txt'

  build-linux-image:
    needs: [ build-jar ]
    name: 'Build Linux Image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Java 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: 'Setup GraalVM Environment'
        uses: DeLaGuardo/setup-graalvm@3.0
        with:
          graalvm-version: '20.3.0.java11'

      - name: 'Install Native Image Plugin'
        run: |
          gu install native-image

      - name: Get version number
        run: |
          echo "VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV

      - name: 'Get JAR Artifact'
        uses: actions/download-artifact@v2-preview
        with:
          name: 'bat-${{env.VERSION}}.jar'

      - name: 'Download Release URL'
        if: contains(github.ref, 'v')
        uses: actions/download-artifact@v2-preview
        with:
          name: 'upload_url.txt'

      - name: 'Set Upload URL Env Var'
        if: contains(github.ref, 'v')
        run: |
          echo "UPLOAD_URL=$(cat upload_url.txt)" >> $GITHUB_ENV

      - name: 'Build Linux Image'
        run: |
          native-image --no-server --no-fallback --allow-incomplete-classpath -jar bat-${{env.VERSION}}.jar

      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: bat-${{env.VERSION}}

      - name: 'Publish Linux Image'
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'bat-${{env.VERSION}}-linux'
          path: 'bat-${{env.VERSION}}'

      - name: 'Upload Linux Image Asset'
        if: success() && contains(github.ref, 'v')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_name: 'bat-${{env.VERSION}}-linux'
          asset_path: 'bat-${{env.VERSION}}'
          asset_content_type: application/octet-stream
